### ISSUE TITLE
GUI not updating with 2.0.0 release

### ISSUE THREAD

**Issue by wyattwww** [Abasz/ESPRowingMonitor-WebGUI#1]
Hi,

I was working off 1.0.1 release and everything was working fine.  When I updated to 2.0.0 release the UI no longer updates and everything stays at 0.  Am I missing anything to get the data to flow again?

Building also produces this warning for web-ant-plus, not sure if it's significant:

Warning: /........./ESPRowingMonitor-WebGUI/src/common/services/ant-heart-rate.service.ts depends on 'web-ant-plus'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Thanks,
Wyatt

**Comment by Abasz** [comment]
Can you please provide me with further info to reproduce? 

Are you running it in dev mode (i.e. npm start) or built and uploaded to the board?

Have you set the websocket address in the settings of the web GUI?

etc.

The error you see on compile is no concern, its standard angular.

**Comment by wyattwww** [comment]
Hi, yes.  I am performing the same steps to get everything onto the ESP32:

1. I update the WebGUI to latest 2.0 tag commit and ESPRowingMonitor to latest commit on Master.
2. I run `ng build` to build the project.
3. I copy the files under the dist/esp-rowing-monitor-client to the ESPRowingMonitor project folder data/www folder.
4. I change into the ESPRowingMonitor folder and run `pio run --target uploadfs --environment esp32` to upload the file system image to the ESP32 chip via USB Serial.
5. In the ESPRowingMonitor project, I select "Upload and Monitor" to build and upload to the ESP32.
6. I open a browser to the ESP and the WebGUI loads after updating the cache, but the metrics don't change.

If I repeat the same steps against the WebGUI 1.01 tag in step one, the WebGUI works again.  Please let me know if I missed a step, or if there's another way to verify and isolate the issue?

Thanks!
Wyatt

**Comment by Abasz** [comment]
Thanks.

Do you see any errors and other info in the browser dev tool? 

What browser do you use? 

Can you please confirm that the websocket connection is available (if the wifi sign in the top left corner is not crossed it should be available)?

Does the timer count or it stays zero? 

The issue is that I cannot reproduce this. In the v2 I only added the ANT+ and BLE HR monitoring.

**Comment by wyattwww** [comment]
No errors in the dev console, I'm using Chrome latest.

The wifi icon is not crossed out and the settings bar looks normal.  The timer does not count and stays at zero.

<img width="1840" alt="image" src="https://github.com/Abasz/ESPRowingMonitor-WebGUI/assets/178768/7c4d777a-7563-4809-a280-bb9b8eec287d">

I'll try to look through the new code changes to see what might be the issue... but it definitely goes back to working when I revert to 1.0.1.  Do I have to update the image for 2.0.0 in any other way than to run pio?

**Comment by wyattwww** [comment]
I tried to build each commit and upload to see where problems start happening and errors start happening with `Add experimental ANT+ Heart Rate monitor support [fec53da]`.  Problems with USBDriver: 

`
Error: src/common/services/ant-heart-rate.service.ts:47:31 - error TS2339: Property 'requestDevice' does not exist on type 'typeof USBDriver'.

47         return from(USBDriver.requestDevice()).pipe(
                                 ~~~~~~~~~~~~~


Error: src/common/services/ant-heart-rate.service.ts:48:13 - error TS2345: Argument of type 'MonoTypeOperatorFunction<unknown>' is not assignable to parameter of type 'OperatorFunction<unknown, USBDriver>'.
  Type 'Observable<unknown>' is not assignable to type 'Observable<USBDriver>'.
    Type 'unknown' is not assignable to type 'USBDriver'.

 48             tap({
                ~~~~~
 49                 error: (error: unknown): void => {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 53                 },
    ~~~~~~~~~~~~~~~~~~
 54             }),
    ~~~~~~~~~~~~~~
`

I can't shake this compile error with subsequent until I point to the 2.0.0 commit and then forcefully cleaning the project by deleting node_modules and running `npm install -force` before running `ng build` again.  But then even though it builds file, the GUI still doesn't update.

Have you tried to clean everything to rebuild to reproduce?  Please let me know what else I can try to troubleshoot.

**Comment by Abasz** [comment]
I was able to reproduce the issue. Its defenately a bug. Thanks for catching it.

It relates to the secureContext part... I will debug this ASAP and push a fix. Actually if you run in dev server mode it will work properly. 

Also a few comments to your above:

- The error you saw on compilation means that you did not do npm install before building. In the commit you mention I added new packages that need install. Hence compilation is successful after npm install. 
- Dont worry about the memory issue that is standard Angular. It does not like chunk sizes above a certain level, it can be changed in angular.json. It means that this app is not lighthouse optimised, its irrelevant for us.

**Comment by Abasz** [comment]
Found the bug. Its of course a silly mistake.

For the sake of speed, can you please change the following in the `heart-rate.service.ts` file:

```ts
streamHeartRate(): Observable<IHeartRate | undefined> {
        if (!isSecureContext) {
            this.snack.open("Heart Rate features are not available, refer to documentation", "Dismiss");

            return EMPTY;
        }

        return this.configManager.config$.pipe(
            filter((config: Config): boolean => config.heartRateMonitor !== this.heartRateMonitor),
            switchMap((config: Config): Observable<IHeartRate | undefined> => {

//...
```
To the following:

```ts
    streamHeartRate(): Observable<IHeartRate | undefined> {
        if (!isSecureContextStub) {
            this.snack.open("Heart Rate features are not available, refer to documentation", "Dismiss");
        }

        return this.configManager.config$.pipe(
            filter(
                (config: Config): boolean =>
                    config.heartRateMonitor !== this.heartRateMonitor && isSecureContext,
            ),
            switchMap((config: Config): Observable<IHeartRate | undefined> => {
//...
```

The issue was that when the browser context is not secure, the `streamHeartRate` observable never emits, but since in the data.service the `withLatestFrom` is used that requires at least one emission from `streamHeartRate`, the data service never emits either...

I will think this through and push a commit with fix later (it is possible that the above is the final version of the solution, but I will need to do some testing to check if anything else may break).

**Comment by wyattwww** [comment]
Yes, that works now!  Had to use  `!isSecureContext` instead of `!isSecureContextStub`, and also remove EMPTY in the import in line 3.  Thank you for the quick update.  Please let me know when you push a proper fix.

FYI I've implemented on a fork FTMS and also Energy kcal metrics as well, I'm just going through testing.  👍
