### ISSUE TITLE
Trouble building - Cannot find module 'ng2-charts' etc

### ISSUE THREAD

**Issue by miyulz** [Abasz/ESPRowingMonitor-WebGUI#2]
Hi, I'm not able to build this. This is my first go at using node and angular.  Do I need to use a specific version of node/angular? 'ng build' gives:

> ./src/main.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
> Error: [BABEL] /home/me/projects-new/ESPRowingMonitor-WebGUI/src/main.ts: Cannot find module './route'
> 
> [LOTS MORE]
> 
> Error: src/app/app.module.ts:38:55 - error NG6002: 'CoreModule' does not appear to be an NgModule class.
> 
> 38     imports: [BrowserModule, BrowserAnimationsModule, CoreModule, webBluetooth],
>  ...............................................................................................~~~~~~~~~~
> 
>   src/common/core.module.ts:54:14
>     54 export class CoreModule {}
> ..............................~~~~~~~~~~
>     Is it missing an @NgModule annotation?
> 

> Error: src/common/core.module.ts:13:32 - error TS2307: Cannot find module 'ng2-charts' or its corresponding type declarations.
> 
> 13 import { NgChartsModule } from "ng2-charts";
>  ......................................................~~~~~~~~~~~~
> 
> 
> Error: src/common/core.module.ts:40:14 - error NG1010:  Value
>

**Comment by Abasz** [comment]
did you install the packages with `npm install` ?

**Comment by miyulz** [comment]
Thanks, works now, I think some file corruption led me down the wrong path.
